# Generated by Django 5.2.1 on 2025-06-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='banner',
        ),
    ]
