# Generated by Django 5.2.1 on 2025-06-15 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='posts.post')),
            ],
        ),
    ]
